   ## Line Detection - Using Hough Lines
   
**cv2.HoughLines**(binarized/thresholded image, 𝜌 accuracy, 𝜃 accuracy, threshold)
- Threshold here is the minimum vote for it to be considered a line


In [44]:
import cv2
import numpy as np

image = cv2.imread('images/soduku.jpg')
cv2.imshow('Original ', image)
cv2.waitKey(0)

# Grayscale and Canny Edges extracted
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
blur = cv2.GaussianBlur(gray, (5,5), 0)
edges = cv2.Canny(blur, 100, 156, apertureSize = 3)


#ret, mask = cv2.threshold(edges, 80, 255, cv2.THRESH_BINARY)
cv2.imshow('Canny edges ', edges)
cv2.waitKey(0)

# Run HoughLines using a rho accuracy of 1 pixel
# theta accuracy of np.pi / 180 which is 1 degree
# Our line threshold is set to 240 (number of points on line)
lines = cv2.HoughLines(edges, 1, np.pi / 180, 180)

print (lines)

# We iterate through each line and convert it to the format
# required by cv.lines (i.e. requiring end points)
for [[rho, theta]] in lines:
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho
    y0 = b * rho
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))
    cv2.line(image, (x1, y1), (x2, y2), (255, 0, 0), 2)

cv2.imshow('Hough Lines', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 637.           1.2566371]]

 [[-437.           2.6529005]]

 [[-380.           2.6529005]]

 [[ -75.           2.8274333]]

 [[-429.           2.6354473]]

 [[-128.           2.7925267]]

 [[-485.           2.6354473]]

 [[ 505.           1.2740903]]

 [[-282.           2.7052603]]

 [[-387.           2.6703537]]

 [[ -24.           2.86234  ]]

 [[ 325.           1.2915436]]

 [[ 322.           1.2915436]]

 [[ 507.           1.2740903]]

 [[-476.           2.6179938]]

 [[ 574.           1.2566371]]

 [[-502.           2.6179938]]

 [[ 381.           1.2915436]]

 [[ 442.           1.2740903]]

 [[-230.           2.7227137]]

 [[-377.           2.6529005]]

 [[-285.           2.7052603]]

 [[-237.           2.740167 ]]

 [[ 437.           1.2915436]]

 [[ -21.           2.86234  ]]

 [[ -78.           2.8274333]]

 [[ 268.           1.3089969]]

 [[ 384.           1.2740903]]

 [[-330.           2.6703537]]

 [[-337.           2.687807 ]]

 [[-131.           2.7925267]]

 [[-434.

### Probabilistic Hough Lines

**cv2.HoughLinesP(binarized image, 𝜌 accuracy, 𝜃 accuracy, threshold, minimum line length, max line gap)




In [78]:
import cv2
import numpy as np

# Grayscale and Canny Edges extracted
image = cv2.imread('images/soduku.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#blur = cv2.GaussianBlur(gray, (5,5), 0)
edges = cv2.Canny(gray, 100, 170, apertureSize = 3)

# Again we use the same rho and theta accuracies
# However, we specific a minimum vote (pts along line) of 100
# and Min line length of 5 pixels and max gap between lines of 10 pixels
lines = cv2.HoughLinesP(edges, 1, np.pi / 180, 1, 3, 3)
print (lines.shape)

for [[x1, y1, x2, y2]] in lines:
    cv2.line(image, (x1, y1), (x2, y2),(0, 255, 0), 3)

cv2.imshow('Probabilistic Hough Lines', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1654, 1, 4)


http://cmp.felk.cvut.cz/~matas/papers/matas-bmvc98.pdf